public class ApexLearning {
    
    public String name;
    public String profession ;
  
    public void getData(){ //METHOD
     

        name = 'Mohammed Salman'; //values
        profession = 'Salesforce Release Engineer'; //values

        name = 'Mohammed Salman';
        profession = 'Salesforce Release Engineer';

        
        System.debug(name);
        System.debug('profession' + profession); //Print statement
        
    } 
    
}
