public class ApexLearning {
    
    public String name;
    public String profession ;
  
    public void getData(){
        name = 'Amar Ganji';
        profession = 'Senior Release Engineer';
        
        System.debug(name);
        System.debug('profession' + profession);
        
    } 
    
}
public class ApexLearning {
    
    public String name;
    public String profession ;
  
    public void getData(){
        name = 'Mohammed Qayum';
        profession = 'Release Engineer';
        
        System.debug(name);
        System.debug('profession' + profession);
        
    } 
    
}