public class IplCricketteams {
    
    public static void main(){
        
        List<string> ChannaiSuperkings = new List<string>();
        ChannaiSuperkings.add('Dhoni');
        ChannaiSuperkings.add('Raina');
        ChannaiSuperkings.add('Jadeja');
        
		List<string> SunrisersHyderabad = new List<string>();
        SunrisersHyderabad.add('David');
        SunrisersHyderabad.add('Samad');
        SunrisersHyderabad.add('Andrew');
        
        system.debug('SunrisersHyderabad ' + 'SunrisersHyderabad');
        system.debug('ChannaiSuperkings ' + 'ChannaiSuperkings');
    }   
    
}