public class LearningApex {
    
	public string name;
    public string profession ;
    
    public void getData(){
        
abdc
        name = 'Mohammed Salam';
        profession = 'Release Engineer';

        name = 'Mohammed Salman';
        profession = 'Software Engineer';
 main
        
        system.debug('test data' + name);
        system.debug ('profession' + profession);
        
    }
}